# This file was generated by GoReleaser. DO NOT EDIT.
class Cidr < Formula
  desc "CIDR is a simple utility to generate the IPv4 addresses in a CIDR range. It could also be used to check the membership of an IP v4 address in a CIDR range"
  homepage "https://github.com/adedayo/cidr"
  version "0.1.5"

  if OS.mac?
    url "https://github.com/adedayo/cidr/releases/download/v0.1.5/cidr_0.1.5_Darwin_x86_64.tar.gz"
    sha256 "927050d478c8035c4a59618598ee3fff1c47a1ccdcc890766fe6a8692c3af642"
  elsif OS.linux?
    url "https://github.com/adedayo/cidr/releases/download/v0.1.5/cidr_0.1.5_Linux_x86_64.tar.gz"
    sha256 "a0a74d75c202e41301673eebf8928bc5a7d08280bb7e7f9d59404bbf8b9c1580"
  end

  def install
    bin.install "cidr"
  end
end
