# This file was generated by GoReleaser. DO NOT EDIT.
class Cidr < Formula
  desc "CIDR is a simple utility to generate the IPv4 addresses in a CIDR range. It could also be used to check the membership of an IP v4 address in a CIDR range"
  homepage "https://github.com/adedayo/cidr"
  version "0.1.4"

  if OS.mac?
    url "https://github.com/adedayo/cidr/releases/download/v0.1.4/cidr_0.1.4_Darwin_x86_64.tar.gz"
    sha256 "23f9ccabb78db101b0ab6b00a00ab58da45eea55fc15727f398779a28dc1638d"
  elsif OS.linux?
    url "https://github.com/adedayo/cidr/releases/download/v0.1.4/cidr_0.1.4_Linux_x86_64.tar.gz"
    sha256 "4b6cc3d9798b301ec649f804bdff5ef043345aa2f096d2b1ae5a942fc5ceca93"
  end

  def install
    bin.install "cidr"
  end
end
