# This file was generated by GoReleaser. DO NOT EDIT.
class ReverseShell < Formula
  desc "reverse-shell is a PoC of a pure Golang reverse shell over TLS"
  homepage "https://github.com/adedayo/reverse-shell"
  version "0.0.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/adedayo/reverse-shell/releases/download/v0.0.2/reverse-shell_0.0.2_Darwin_x86_64.tar.gz"
    sha256 "39c4be215b5a914a0f2ba32c01626c868ef80a0dbe43406f1eb97381f758b4ee"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/adedayo/reverse-shell/releases/download/v0.0.2/reverse-shell_0.0.2_Linux_x86_64.tar.gz"
      sha256 "fe55d9dcf5c507e791a5c851abb07b33c8840fc5684f5ec3b3297d44a74c580f"
    end
  end

  def install
    bin.install "reverse-shell-client"
    bin.install "reverse-shell-server"
  end
end
