# This file was generated by GoReleaser. DO NOT EDIT.
class Tcpscan < Formula
  desc "TCPScan is a simple utility for discovering open (or closed) TCP ports on servers. It uses gopacket(https://github.com/google/gopacket) to craft SYN packets, listening asynchronously for (SYN-)ACK or RST responses without completing the full TCP handshake. TCPScan uses goroutines for asynchronous scans and it searches for the most likely listening ports first, using NMap's port frequency ordering. Anecdotal results show that TCPScan is really fast!"
  homepage "https://github.com/adedayo/tcpscan"
  version "0.5.9"

  if OS.mac?
    url "https://github.com/adedayo/tcpscan/releases/download/v0.5.9/tcpscan_0.5.9_Darwin_x86_64.tar.gz"
    sha256 "26551e636fef0309fcc2df9245b2bfc65f1d8445034c66e54879708f98a53d57"
  elsif OS.linux?
  end

  def install
    bin.install "tcpscan"
  end
end
