# This file was generated by GoReleaser. DO NOT EDIT.
cask "checkmate" do
  version "1.1.9"

  on_macos do
    on_intel do
      sha256 "02be3664542ff2cfc28524a6c4b4c8ffb02565ca7015b6afb449b684c4191e3f"
      url "https://github.com/adedayo/checkmate/releases/download/v#{version}/checkmate_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8f15050211654b6af62cc711f0edef167de2abb7f1d65dbcab908b0c073d5174"
      url "https://github.com/adedayo/checkmate/releases/download/v#{version}/checkmate_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "3a9f783074f832e32e8e36023d8a04809aba0e6384cd1cb42324b31a0791e472"
      url "https://github.com/adedayo/checkmate/releases/download/v#{version}/checkmate_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "8a281c9e4f5b6e9c5ef6c9e9b16ed4e1159d26f5372eaba3e26fb4521cfcbaac"
      url "https://github.com/adedayo/checkmate/releases/download/v#{version}/checkmate_Linux_arm64.tar.gz"
    end
  end

  name "checkmate"
  desc "CheckMate is a code security analysis tool."
  homepage "https://github.com/adedayo/checkmate"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "checkmate"

  # No zap stanza required

  caveats <<~EOS
    To get help running CheckMate please run: checkmate --help
  EOS
end
