# This file was generated by GoReleaser. DO NOT EDIT.
cask "dnsaudit" do
  version "1.0.3"

  on_macos do
    on_intel do
      sha256 "78afad3ab7c636d8cf660c22b67b3ef36381753d1aa5069594568c48b1d73840"
      url "https://github.com/adedayo/dnsaudit/releases/download/v#{version}/dnsaudit_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e89b7cedd68ddfd03926ed470910baf5e4149ae7fc601dc7e1951da6c9a0c90e"
      url "https://github.com/adedayo/dnsaudit/releases/download/v#{version}/dnsaudit_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "981aa237a3de6cf6701eaf892a319b0e60db5cede219b4325c4f93fe434772c9"
      url "https://github.com/adedayo/dnsaudit/releases/download/v#{version}/dnsaudit_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "de37d910caeb37718402c3cd6567f0d8381e8c7eedfac223a59a9592d7d4b3d3"
      url "https://github.com/adedayo/dnsaudit/releases/download/v#{version}/dnsaudit_#{version}_linux_arm64.tar.gz"
    end
  end

  name "dnsaudit"
  desc "Audit security posture by interrogating the DNS."
  homepage "https://github.com/adedayo/dnsaudit"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "dnsaudit"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/dnsaudit"]
    end
  end

  zap trash: [
      "~/Library/Caches/dnsaudit",
    ]

  caveats <<~EOS
    To get started, run: dnsaudit --help
  EOS
end
