# This file was generated by GoReleaser. DO NOT EDIT.
cask "vantage" do
  version "1.3.0"

  on_macos do
    on_intel do
      sha256 "80e393f1a8829aff94d9c992bccd592041e250498781dc3218f485c249b6a150"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "36a957922d5a22a6c3eb50358b29ff58f07bb8b500c90575bf723fb8aef5114c"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9e3a03de406513d3c7028b6dc8bfacf294ddf80f836aefb2598115861355f492"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9c30ca3da14637af3fa0d398e5a89edb23873707161a4d7180c1acf3500e87a3"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vantage"
  desc "See what an attacker sees: audit the attack surface an organisation exposes."
  homepage "https://github.com/adedayo/vantage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vantage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vantage"]
    end
  end

  zap trash: [
      "~/Library/Caches/vantage",
    ]

  caveats <<~EOS
    To get started, run: vantage --help
  EOS
end
