# This file was generated by GoReleaser. DO NOT EDIT.
cask "vantage" do
  postflight_steps do
    run "/usr/bin/xattr",
        args:         ["-dr", "com.apple.quarantine", "vantage"],
        chdir:        ".",
        must_succeed: false
  end

  version "1.6.1"

  on_macos do
    on_arm do
      sha256 "3826c70c142034bb7629c24044a5284749e76febca6e0b597619fce4a3fe2298"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "e3e6c21b0fa7dd11be94d0af6f167f4d18d6c26d4137b4ccc4dbd8c35860eddc"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "aab06f5c1b14bcde8e22c147d2371346180b3c502fd5a73fd337862769699427"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "3ed8d2f95fc49949b956a7a98a345c9c5fb894fbe6d02b5e1bc926ad6838311a"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_linux_amd64.tar.gz"
    end
  end

  name "vantage"
  desc "See what an attacker sees: audit the attack surface an organisation exposes."
  homepage "https://github.com/adedayo/vantage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vantage"

  zap trash: [
      "~/Library/Caches/vantage",
    ]

  caveats <<~EOS
    To get started, run: vantage --help
  EOS
end
