# This file was generated by GoReleaser. DO NOT EDIT.
cask "vantage" do
  version "1.2.0"

  on_macos do
    on_intel do
      sha256 "7d9a7fcbcd49c097552e3783e7cb520bba835728947d722e6fdc929066152b40"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0dea553696f9433518c9f2b4f59ddbf72ed03b12afc9cbbc1a52085b83cf8488"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ec9ab899939d652c92a53f670404e5b02657ae07917a178e6c7ffcda40a51d0d"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "21ae08cb52f66deab33960c826a706a70918c70cea5c9ecc0fb0315848dead79"
      url "https://github.com/adedayo/vantage/releases/download/v#{version}/vantage_#{version}_linux_arm64.tar.gz"
    end
  end

  name "vantage"
  desc "See what an attacker sees: audit the attack surface an organisation exposes."
  homepage "https://github.com/adedayo/vantage"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "vantage"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/vantage"]
    end
  end

  zap trash: [
      "~/Library/Caches/vantage",
    ]

  caveats <<~EOS
    To get started, run: vantage --help
  EOS
end
